language: go
#dist: xenial

go:
  - "1.11"

matrix:
  include:
  #- dist: xenial
  - os: osx

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r'
    - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - llvm-7-dev
    - clang-7
    - libclang-7-dev
    - binutils-arm-none-eabi
    - qemu-system-arm
  homebrew:
    update: true
    packages:
    - llvm
    #- dep

#install:

script:
  - mkdir -p /Users/travis/gopath/bin
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure --vendor-only
  - go install github.com/aykevl/tinygo
  #- ls -l /usr/local/Cellar
  #- ls -l /usr/local/Cellar/llvm
  #- ls -l /usr/local/Cellar/llvm/7.0.1/lib
  #- ls -l /usr/local/opt/llvm/include
  #- find /usr/local -name Analysis.h
  #- find /usr/local -name Index.h
  - go test -v .
  - make gen-device
  - tinygo build -o blinky1.nrf.elf    -target=pca10040     examples/blinky1
  - tinygo build -o blinky2.nrf.elf    -target=pca10040     examples/blinky2
  - tinygo build -o blinky2                                 examples/blinky2
  - tinygo build -o test.nrf.elf       -target=pca10040     examples/test
  - tinygo build -o blinky1.nrf51.elf  -target=microbit     examples/echo
  - tinygo build -o test.nrf.elf       -target=nrf52840-mdk examples/blinky1
  - tinygo build -o blinky1.nrf51d.elf -target=pca10031     examples/blinky1
  - tinygo build -o blinky1.stm32.elf  -target=bluepill     examples/blinky1
  - tinygo build -o blinky1.avr.o      -target=arduino      examples/blinky1 # TODO: avr-as/avr-gcc doesn't work
  - tinygo build -o blinky1.reel.elf   -target=reelboard    examples/blinky1
  - tinygo build -o blinky2.reel.elf   -target=reelboard    examples/blinky2
  - tinygo build -o blinky1.pca10056.elf    -target=pca10056     examples/blinky1
  - tinygo build -o blinky2.pca10056.elf    -target=pca10056     examples/blinky2
  - tinygo build -o blinky1.samd21.elf    -target=itsybitsy-m0     examples/blinky1
